### ISSUE TITLE
Consider reverting default build target back to stock Pico

### ISSUE THREAD

**Issue by recursivenomad** [raspberrypi/debugprobe#142]
It seems that when renaming the project from "picoprobe" to "debugprobe", the default build target [was changed](https://github.com/raspberrypi/debugprobe/commit/d0c03d2564fb6aa2cccfe9e08f48efe7e2463ace#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L27) [to the](https://github.com/raspberrypi/debugprobe/commit/d0c03d2564fb6aa2cccfe9e08f48efe7e2463ace#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aL48) [debugprobe hardware](https://github.com/raspberrypi/debugprobe/commit/d0c03d2564fb6aa2cccfe9e08f48efe7e2463ace#diff-84ca4a39ea43cf837b0506624b40305b6932dbb968d19beefdf88ce8365a3558L68).

My understanding is that most people building this repository are doing so on stock Picos, and guides from before this change understandably do not mention needing this CMake flag.

To maintain ease of use and backwards-compatibility, I suggest reverting the default build target back to the stock Pico.

**Comment by nathan-contino** [comment]
Thanks for the feedback. Our primary documentation for `debugprobe` lives in the Getting Started with Pico book, which includes [extensive information about building for both Pico and the Debug Probe in 'Appendix A: Using debugprobe'](https://datasheets.raspberrypi.com/pico/getting-started-with-pico.pdf). This repo also includes instructions for both build targets in the [README](https://github.com/raspberrypi/debugprobe/blob/master/README.md).

Because the documentation covers both use cases, I think it's safe to leave the Debug Probe hardware as the default build target; it's not as if including the `-DDEBUG_ON_PICO=ON` option is especially difficult! So this should be safe to close.
